# Generated by Django 5.0.4 on 2024-04-15 06:10

import datetime
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Chauffeur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50)),
                ('prenoms', models.CharField(max_length=50)),
                ('tel', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Ecole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=150, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Itineraire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_itineraire', models.DateField(default=datetime.date.today, null=True)),
                ('ligne_inverse', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='LieuLigne',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_lieu', models.CharField(max_length=50)),
                ('latitude', models.CharField(default='-18.881589691375204', max_length=50)),
                ('longitude', models.CharField(default='47.50664234161377', max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Ligne',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Parent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_mere', models.CharField(max_length=50, null=True)),
                ('nom_pere', models.CharField(max_length=50, null=True)),
                ('tel_mere', models.CharField(max_length=50, null=True)),
                ('tel_pere', models.CharField(max_length=50, null=True)),
                ('email', models.EmailField(max_length=254, null=True, unique=True)),
                ('adresse', models.CharField(max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TypeVehicule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50, verbose_name='Nom Type Vehicule')),
            ],
        ),
        migrations.CreateModel(
            name='Bus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('immatriculation', models.CharField(max_length=50, verbose_name='Immatruculation')),
                ('couleur', models.CharField(max_length=50, null=True)),
                ('nbr_place', models.IntegerField()),
                ('chauffeur', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='transport_scolaire.chauffeur')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transport_scolaire.typevehicule')),
            ],
        ),
        migrations.CreateModel(
            name='Classe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50, unique=True)),
                ('ecole', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='transport_scolaire.ecole')),
            ],
        ),
        migrations.CreateModel(
            name='Eleve',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_inscription', models.DateField(default=datetime.date.today)),
                ('date_naissance', models.DateField(null=True)),
                ('image', models.ImageField(null=True, upload_to='')),
                ('nom', models.CharField(max_length=100)),
                ('prenoms', models.CharField(max_length=100)),
                ('adresse', models.CharField(max_length=100)),
                ('montant_frais', models.DecimalField(blank=True, decimal_places=2, max_digits=10, max_length=50, null=True)),
                ('etat', models.CharField(default='en_attente', max_length=50)),
                ('classe', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='transport_scolaire.classe')),
                ('ecole', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='transport_scolaire.ecole')),
            ],
        ),
        migrations.CreateModel(
            name='BusAssignation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_assignation', models.DateField(default=django.utils.timezone.now)),
                ('bus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transport_scolaire.bus')),
                ('itineraire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transport_scolaire.itineraire')),
            ],
        ),
        migrations.CreateModel(
            name='AssignationItineraire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dateAssigntion', models.DateField(default=django.utils.timezone.now)),
                ('eleve', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='transport_scolaire.eleve')),
                ('itineraire', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='transport_scolaire.itineraire')),
            ],
        ),
        migrations.CreateModel(
            name='Horaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heureDebut', models.TimeField()),
                ('heureFin', models.TimeField()),
                ('itineraire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transport_scolaire.itineraire')),
                ('pointArret', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transport_scolaire.lieuligne')),
            ],
        ),
        migrations.CreateModel(
            name='LieuRamassage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_lieu', models.CharField(max_length=50)),
                ('latitude', models.CharField(default='-18.881589691375204', max_length=50, null=True)),
                ('longitude', models.CharField(default='47.50664234161377', max_length=50, null=True)),
                ('lieu_ligne', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='transport_scolaire.lieuligne')),
                ('ligne', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='transport_scolaire.ligne')),
            ],
        ),
        migrations.AddField(
            model_name='eleve',
            name='lieu_ramassage',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='transport_scolaire.lieuramassage', verbose_name='lieu de ramassage'),
        ),
        migrations.AddField(
            model_name='itineraire',
            name='ligne',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transport_scolaire.ligne'),
        ),
        migrations.AddField(
            model_name='eleve',
            name='ligne',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='transport_scolaire.ligne'),
        ),
        migrations.CreateModel(
            name='OrdreLieu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_ordre', models.IntegerField()),
                ('lieu_ligne', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transport_scolaire.lieuligne')),
                ('ligne', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transport_scolaire.ligne')),
            ],
        ),
        migrations.AddField(
            model_name='eleve',
            name='parent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='transport_scolaire.parent'),
        ),
    ]
