# Generated by Django 5.0.4 on 2024-05-13 06:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transport_scolaire', '0002_eleve_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='eleve',
            name='lieu_remisage',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='eleves', to='transport_scolaire.lieuramassage', verbose_name='lieu de remisage'),
        ),
    ]
