# Generated by Django 5.0.4 on 2024-05-13 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transport_scolaire', '0003_eleve_lieu_remisage'),
    ]

    operations = [
        migrations.AddField(
            model_name='eleve',
            name='type_inscription',
            field=models.CharField(choices=[('ramasse et remisage', 'Ramasse et Remisage'), ('ramassage', 'Ramassage'), ('remisage', 'Remisage')], max_length=50, null=True),
        ),
    ]
