# Generated by Django 5.0.4 on 2024-05-13 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transport_scolaire', '0004_eleve_type_inscription'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eleve',
            name='type_inscription',
            field=models.CharField(choices=[('ramasse et remisage', 'Ramasse et Remisage'), ('ramassage', 'Ramassage'), ('remisage', 'Remisage')], default='ramassage', max_length=50),
        ),
    ]
