# Generated by Django 5.0.4 on 2024-05-14 05:06

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transport_scolaire', '0005_alter_eleve_type_inscription'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignationitineraire',
            name='bus',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='transport_scolaire.bus'),
        ),
        migrations.CreateModel(
            name='EcoleAssignation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_assignation', models.DateField(default=django.utils.timezone.now)),
                ('ecole', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transport_scolaire.ecole')),
                ('itineraire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transport_scolaire.itineraire')),
            ],
        ),
    ]
