# Generated by Django 5.0.4 on 2024-04-15 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('PARENT', 'Parent'), ('ECOLE', 'Ecole')], max_length=30, verbose_name='Rôle'),
        ),
    ]
